-- ================================================================
-- Explicaciones para las 60 preguntas de TaskFlow
-- ================================================================

-- Cuestionario 2: ¿Qué es Scrum?
UPDATE preguntas SET explicacion = 'Scrum es un framework ágil liviano creado por Ken Schwaber y Jeff Sutherland. A diferencia de los métodos en cascada (que planifican todo al inicio), Scrum entrega valor en ciclos cortos llamados Sprints y se adapta continuamente al cambio.' WHERE id = 1;
UPDATE preguntas SET explicacion = 'La Scrum Guide establece que un Sprint tiene una duración máxima de 4 semanas y mínima de 1 semana. Los Sprints más cortos generan feedback más frecuente y reducen el riesgo. La duración se fija y no cambia durante el proyecto.' WHERE id = 2;
UPDATE preguntas SET explicacion = 'Los 5 valores de Scrum son: Compromiso, Foco, Apertura, Respeto y Coraje. El Compromiso implica dedicación a los objetivos del equipo, no solo a las tareas individuales. Competencia, Jerarquía y Control no son valores Scrum.' WHERE id = 3;
UPDATE preguntas SET explicacion = 'El empirismo en Scrum significa que las decisiones se toman basándose en lo que se observa y experimenta, no en suposiciones. Sus tres pilares son: Transparencia, Inspección y Adaptación. Scrum no se basa en planificación detallada ni en supuestos.' WHERE id = 4;
UPDATE preguntas SET explicacion = 'Scrum tiene exactamente 5 valores: Compromiso, Foco, Apertura, Respeto y Coraje. Estos valores no son opcionales, son el fundamento que hace que los pilares del empirismo (Transparencia, Inspección, Adaptación) cobren vida.' WHERE id = 5;

-- Cuestionario 4: Roles en Scrum
UPDATE preguntas SET explicacion = 'El Product Owner es la única persona responsable de maximizar el valor del producto. Gestiona y prioriza el Product Backlog. No es un comité ni un grupo — es una sola persona con autoridad para tomar decisiones sobre qué construir y en qué orden.' WHERE id = 6;
UPDATE preguntas SET explicacion = 'El Scrum Master es un líder servicial cuya función principal es facilitar el proceso Scrum y eliminar impedimentos externos que bloquean al equipo. No escribe código, no gestiona presupuestos ni define requisitos — esas son responsabilidades de otros roles.' WHERE id = 7;
UPDATE preguntas SET explicacion = 'Los Developers son autogestionados: deciden internamente cómo hacer el trabajo. El Product Owner decide QUÉ construir, pero los Developers deciden CÓMO. Esto es fundamental para la autogestión del equipo Scrum.' WHERE id = 8;
UPDATE preguntas SET explicacion = 'Scrum tiene exactamente 3 roles: Product Owner, Scrum Master y Developers. No hay sub-roles, ni líder técnico separado, ni gerente de proyecto. Esta simplicidad es intencional — reduce la burocracia y fomenta la autogestión.' WHERE id = 9;
UPDATE preguntas SET explicacion = 'El Product Owner es responsable de gestionar y priorizar el Product Backlog. Decide qué items van primero según el valor que aportan al producto. Aunque cualquiera puede proponer items, solo el PO decide el orden y prioridad.' WHERE id = 10;

-- Cuestionario 6: Ceremonias de Scrum
UPDATE preguntas SET explicacion = 'El Daily Scrum es una reunión de 15 minutos donde los Developers sincronizan su trabajo y adaptan el plan del día hacia el Sprint Goal. No es un reporte de estado para el Scrum Master — es una reunión táctica del equipo para sí mismo.' WHERE id = 11;
UPDATE preguntas SET explicacion = 'El Daily Scrum dura exactamente 15 minutos, todos los días, sin excepciones. Si surgen conversaciones más profundas, se continúan fuera del Daily. Esta restricción mantiene la reunión enfocada y evita que se convierta en una reunión improductiva.' WHERE id = 12;
UPDATE preguntas SET explicacion = 'La Retrospectiva tiene como objetivo mejorar el proceso de trabajo del equipo. El equipo reflexiona sobre qué salió bien, qué no funcionó y qué acciones concretas tomará. Produce al menos una mejora que se incorpora al siguiente Sprint.' WHERE id = 13;
UPDATE preguntas SET explicacion = 'La Sprint Review ocurre al final del Sprint para inspeccionar el Increment con los stakeholders y adaptar el Product Backlog según el feedback. Es una sesión colaborativa de trabajo, no una presentación formal.' WHERE id = 14;
UPDATE preguntas SET explicacion = 'El Sprint Planning ocurre al inicio de cada Sprint. El equipo selecciona items del Product Backlog que puede completar y crea el Sprint Backlog. También define el Sprint Goal: el objetivo que hace valioso al Sprint.' WHERE id = 15;

-- Cuestionario 8: Artefactos de Scrum
UPDATE preguntas SET explicacion = 'El compromiso del Product Backlog es el Product Goal: el objetivo a largo plazo del producto hacia el cual trabaja el equipo. El Sprint Goal es el compromiso del Sprint Backlog, y la Definition of Done es el compromiso del Increment.' WHERE id = 16;
UPDATE preguntas SET explicacion = 'El Sprint Backlog contiene tres elementos: el Sprint Goal (por qué), los items seleccionados del Product Backlog (qué) y el plan de acción de los Developers (cómo). Es creado por los Developers durante el Sprint Planning.' WHERE id = 17;
UPDATE preguntas SET explicacion = 'El Increment es la suma acumulada de todos los items completados que cumplen la Definition of Done. Debe ser utilizable y potencialmente entregable al final de cada Sprint. Si un item no cumple la DoD, no forma parte del Increment.' WHERE id = 18;
UPDATE preguntas SET explicacion = 'Scrum tiene exactamente 3 artefactos: Product Backlog, Sprint Backlog e Increment. Cada uno tiene un compromiso asociado: Product Goal, Sprint Goal y Definition of Done respectivamente.' WHERE id = 19;
UPDATE preguntas SET explicacion = 'Cualquier persona puede proponer items al Product Backlog (stakeholders, desarrolladores, el Scrum Master), pero el Product Owner es el único con autoridad para decidir la prioridad y el orden. Esta distinción es clave en Scrum.' WHERE id = 20;

-- Cuestionario 9: Examen Final Básico (situacional)
UPDATE preguntas SET explicacion = 'Cuando el Sprint Goal se vuelve obsoleto, el Product Owner puede cancelar el Sprint. Si el objetivo sigue siendo válido pero el cliente cambió de opinión sobre algunas funcionalidades, el Scrum Master protege el Sprint Goal y las nuevas necesidades se incorporan al Product Backlog para el siguiente Sprint.' WHERE id = 21;
UPDATE preguntas SET explicacion = 'Los Developers gestionan el Sprint Backlog y conocen su capacidad real. Agregar trabajo a mitad del Sprint sin su consenso compromete la calidad y el Sprint Goal. El Product Owner puede negociar quitando otros items del Sprint si considera urgente la nueva tarea.' WHERE id = 22;
UPDATE preguntas SET explicacion = 'El resultado más valioso de una Sprint Review donde el cliente dice "esto no es lo que pedimos" es actualizar el Product Backlog con las nuevas prioridades aprendidas. El feedback negativo es información valiosa que guía el trabajo futuro.' WHERE id = 23;
UPDATE preguntas SET explicacion = 'Si en cada Retrospectiva se identifican los mismos problemas sin cambios, la Retrospectiva no está generando acciones concretas. El equipo debe comprometerse con al menos una mejora implementable en el siguiente Sprint. Sin acción, la Retrospectiva pierde su valor.' WHERE id = 24;
UPDATE preguntas SET explicacion = 'La Definition of Done es un estándar de calidad no negociable. Si un item no la cumple (por ejemplo, no pasó pruebas de integración), no puede incluirse en el Increment. Se mueve al Product Backlog para completarse en el siguiente Sprint.' WHERE id = 25;
UPDATE preguntas SET explicacion = 'El Sprint Goal es el objetivo que da valor al Sprint (el "por qué"). El Sprint Backlog es el conjunto de items seleccionados y el plan para lograr ese objetivo (el "qué" y el "cómo"). Son complementarios pero distintos.' WHERE id = 26;
UPDATE preguntas SET explicacion = 'El Daily Scrum es para los Developers. El Scrum Master protege al equipo de interrupciones externas, incluyendo a gerentes que intenten participar activamente. Los externos pueden observar en silencio, pero no deben dirigir preguntas al equipo durante la reunión.' WHERE id = 27;
UPDATE preguntas SET explicacion = 'La velocidad histórica es la mejor guía para planificar. Si el equipo completa consistentemente entre 18 y 22 SP, comprometerse con ~20 SP es realista. Comprometerse con más genera estrés y deuda técnica; con menos desperdicia capacidad.' WHERE id = 28;
UPDATE preguntas SET explicacion = 'Cada equipo define su propia escala de Story Points basada en su contexto, tecnología y experiencia. Un equipo con 40 SP puede estar usando historias más pequeñas que otro con 20 SP. Comparar velocidades entre equipos es una mala práctica que no mide productividad real.' WHERE id = 29;
UPDATE preguntas SET explicacion = '"Potencialmente entregable" significa que el Increment cumple la Definition of Done y podría usarse en producción si el Product Owner lo decide. No significa que obligatoriamente se lanzará al cliente — esa es una decisión de negocio separada.' WHERE id = 30;

-- Cuestionario 11: Estimación y Planificación
UPDATE preguntas SET explicacion = 'Los Story Points miden el esfuerzo, complejidad e incertidumbre de una historia de forma relativa, no absoluta. No son horas. Decir "esta historia vale 8 SP" significa que es aproximadamente el doble de compleja que una de 4 SP, sin importar cuántas horas tome.' WHERE id = 31;
UPDATE preguntas SET explicacion = 'Planning Poker usa la escala de Fibonacci (1, 2, 3, 5, 8, 13, 21) con cartas. Todos revelan simultáneamente para evitar el "anchoring bias" — el sesgo de ajustarse al número que alguien dijo primero. Las diferencias grandes generan discusión valiosa.' WHERE id = 32;
UPDATE preguntas SET explicacion = 'La velocidad es la cantidad de Story Points que el equipo completa por Sprint, calculada como promedio de los últimos 3-5 Sprints. Es una métrica de planificación interna, no un indicador de productividad individual ni algo para comparar entre equipos.' WHERE id = 33;
UPDATE preguntas SET explicacion = 'Conocer la velocidad permite predecir cuánto trabajo puede completar el equipo en futuros Sprints. Si el backlog tiene 200 SP y la velocidad es 40 SP/Sprint, se necesitan aproximadamente 5 Sprints. Esto ayuda a gestionar expectativas y fechas de entrega.' WHERE id = 34;
UPDATE preguntas SET explicacion = 'Los Developers estiman porque son quienes harán el trabajo. El Product Owner puede clarificar el alcance, pero no puede imponer estimaciones. El Scrum Master facilita el proceso pero no estima. Las estimaciones son responsabilidad de quien ejecuta el trabajo.' WHERE id = 35;

-- Cuestionario 13: Refinamiento del Backlog
UPDATE preguntas SET explicacion = 'La Definition of Done es un acuerdo formal del equipo que define los criterios de calidad que debe cumplir todo trabajo para considerarse completo. Incluye pruebas, documentación, revisión de código, etc. Es el estándar de calidad del Increment.' WHERE id = 36;
UPDATE preguntas SET explicacion = 'La Definition of Ready define los criterios que debe cumplir un item del backlog para poder seleccionarse en el Sprint Planning. Por ejemplo: tiene criterios de aceptación claros, está estimado y no tiene dependencias bloqueantes.' WHERE id = 37;
UPDATE preguntas SET explicacion = 'La Scrum Guide recomienda dedicar no más del 10% de la capacidad del equipo al refinamiento. Más tiempo significaría menos tiempo para desarrollar. El refinamiento es continuo pero no debe dominar el Sprint.' WHERE id = 38;
UPDATE preguntas SET explicacion = 'Los criterios de aceptación son las condiciones específicas, claras y medibles que debe cumplir una historia para ser aceptada por el Product Owner. "Debe ser rápido" no es un criterio aceptable; "debe cargar en menos de 2 segundos" sí lo es.' WHERE id = 39;
UPDATE preguntas SET explicacion = 'El refinamiento es una actividad del Scrum Team completo. Los Developers aportan perspectiva técnica (estimaciones, dependencias), el Product Owner aclara el valor y los criterios. La colaboración produce items mejor definidos y estimados.' WHERE id = 40;

-- Cuestionario 15: Métricas en Scrum
UPDATE preguntas SET explicacion = 'El Burndown Chart muestra el trabajo RESTANTE a lo largo del tiempo (eje X = días del Sprint, eje Y = Story Points pendientes). Una línea va bajando desde el total hasta cero si todo va según el plan.' WHERE id = 41;
UPDATE preguntas SET explicacion = 'El Burndown muestra trabajo RESTANTE (baja hacia cero). El Burnup muestra trabajo COMPLETADO (sube hacia el total). La ventaja del Burnup es que también visualiza el scope creep: cuando se agregan tareas, la línea de alcance sube.' WHERE id = 42;
UPDATE preguntas SET explicacion = 'El Cycle Time mide el tiempo desde que el equipo EMPIEZA a trabajar en un item hasta que lo entrega. El Lead Time mide desde que se SOLICITA hasta que se entrega (incluye el tiempo de espera). Cycle Time ≤ Lead Time siempre.' WHERE id = 43;
UPDATE preguntas SET explicacion = 'Las métricas en Scrum sirven para inspeccionar el proceso y adaptarlo, no para controlar ni castigar al equipo. Se usan en la Retrospectiva para identificar mejoras. Usarlas para evaluar rendimiento individual es una mala práctica.' WHERE id = 44;
UPDATE preguntas SET explicacion = 'Una velocidad inconsistente entre Sprints puede indicar problemas en el proceso (impedimentos no resueltos), variación en el equipo (personas que entran o salen), deuda técnica acumulada, o problemas de estimación. Debe investigarse, no ignorarse.' WHERE id = 45;

-- Cuestionario 17: Scrum a Escala
UPDATE preguntas SET explicacion = 'Scrum of Scrums es una técnica simple donde un representante de cada equipo Scrum se reúne regularmente (generalmente 3 veces por semana) para sincronizar avances, identificar dependencias entre equipos y resolver impedimentos compartidos.' WHERE id = 46;
UPDATE preguntas SET explicacion = 'SAFe significa Scaled Agile Framework. Es el framework de escalado más adoptado en empresas grandes. Organiza equipos en Agile Release Trains (ARTs) y añade niveles de programa y portafolio sobre el nivel de equipo.' WHERE id = 47;
UPDATE preguntas SET explicacion = 'LeSS significa Large-Scale Scrum. Aplica los principios de Scrum a múltiples equipos trabajando en un solo producto con un solo Product Backlog y un solo Product Owner. Es menos prescriptivo que SAFe y busca la simplicidad.' WHERE id = 48;
UPDATE preguntas SET explicacion = 'Se necesita escalar Scrum cuando un producto es tan grande que un solo equipo Scrum no puede desarrollarlo en un tiempo razonable y se requieren múltiples equipos trabajando en paralelo sobre el mismo producto.' WHERE id = 49;
UPDATE preguntas SET explicacion = 'El principal desafío de escalar Scrum es coordinar múltiples equipos manteniendo la agilidad de cada uno. Sin coordinación, los equipos crean dependencias bloqueantes e integración difícil. Con demasiada coordinación, se pierde la agilidad.' WHERE id = 50;

-- Cuestionario 18: Examen Final Avanzado (situacional)
UPDATE preguntas SET explicacion = 'Con velocidad de 30 SP y backlog de 180 SP: 180 / 30 = 6 Sprints. La duración del Sprint (2 semanas) es un dato contextual pero no afecta el cálculo de número de Sprints — solo permite saber el tiempo total (6 × 2 = 12 semanas).' WHERE id = 53;
UPDATE preguntas SET explicacion = 'Cuando el Burndown muestra retraso, el equipo debe actuar en el Daily Scrum: identificar qué está bloqueando el avance y adaptar el plan (quitar scope, pedir ayuda, resolver impedimentos). Ignorarlo o extender el Sprint no son respuestas Scrum válidas.' WHERE id = 54;
UPDATE preguntas SET explicacion = 'Criterios de aceptación vagos como "debe ser rápido" no son específicos ni medibles, por lo que el item no cumple la Definition of Ready. Los criterios deben ser objetivamente verificables para que los Developers puedan saber cuándo el trabajo está terminado.' WHERE id = 56;
UPDATE preguntas SET explicacion = 'Un ART (Agile Release Train) en SAFe es un equipo de equipos Scrum (típicamente 50-125 personas) alineados en un flujo de valor común. Todos los equipos del ART trabajan en ciclos sincronizados llamados Program Increments (PI).' WHERE id = 59;
UPDATE preguntas SET explicacion = 'El Scrum of Scrums sirve para sincronizar dependencias entre equipos e identificar impedimentos compartidos. No reemplaza los Daily Scrums de cada equipo ni es para reportar a la gerencia — es una coordinación horizontal entre equipos.' WHERE id = 60;
UPDATE preguntas SET explicacion = 'Cuando la velocidad baja significativamente (de 40 a 22 SP), el primer paso es investigar en la Retrospectiva qué cambió: ¿hubo cambios en el equipo? ¿deuda técnica? ¿impedimentos nuevos? ¿estimaciones infladas antes? Presionar al equipo sin entender la causa empeora la situación.' WHERE id = 51;
UPDATE preguntas SET explicacion = 'En Planning Poker, cuando hay una divergencia grande (3 vs 21), el protocolo es pedir al extremo que explique su razonamiento. La persona que votó 21 puede estar viendo riesgos técnicos, dependencias o complejidad oculta que los demás no consideraron.' WHERE id = 52;
UPDATE preguntas SET explicacion = 'El principal desafío de 5 equipos en el mismo producto es coordinar dependencias sin perder la agilidad de cada equipo. Técnicas como Scrum of Scrums, LeSS o SAFe ayudan a sincronizar sin crear burocracia excesiva.' WHERE id = 55;
UPDATE preguntas SET explicacion = 'La deuda técnica debe gestionarse como cualquier otro trabajo: creando items en el Product Backlog y priorizándolos junto con las demás historias. El Product Owner debe entender el impacto de la deuda técnica para priorizarla adecuadamente.' WHERE id = 57;
UPDATE preguntas SET explicacion = 'SAFe significa Scaled Agile Framework. Es el framework de escalado más adoptado empresarialmente. Tiene múltiples niveles (equipo, programa, portafolio) y organiza equipos en ARTs. Es más prescriptivo que LeSS pero más adoptado en grandes organizaciones.' WHERE id = 58;

